CREATE TABLE PRODUCT (
	Product_Id VARCHAR2(20) PRIMARY KEY,
	Product_Name VARCHAR2(20) NOT NULL,
	Price NUMBER CHECK(>0)
);

CREATE TABLE CUSTOMER (
	Customer_Id VARCHAR2(20) PRIMARY KEY,
	Customer_Name VARCHAR2(20) NOT NULL,
	Customer_Tel NUMBER
);

CREATE TABLE ORDERS (
	Customer_Id VARCHAR2(20) FO ,
	Product_Id VARCHAR2(20),
	Quantity NUMBER,
	Total_amount NUMBER
);

/*Add a foreign key*/

ALTER TABLE ORDERS
ADD FOREIGN KEY(PRODUCT)
REFERENCES PRODUCT(Product_Id)
ON DELETE SET NULL;
ALTER TABLE ORDERS
ADD FOREIGN KEY(CUSTOMER)
REFERENCES CUSTOMER(Customer_Id)
ON DELETE SET NULL;

/*Add a column*/

ALTER TABLE PRODUCT ADD Category VARCHAR2(20);
ALTER TABLE ORDERS ADD OrderDate DATE DEFAULT(SYSDATE) ;
